### ISSUE TITLE
1.21.x

### ISSUE THREAD

**Issue by Jackuhlf** [kryparnold/item-frames-plus#2]
Hey! Wondering if this mod will be updated for 1.21.1/2/3? Could really use it.

**Comment by emirhanpisgin** [comment]
> Hey! Wondering if this mod will be updated for 1.21.1/2/3? Could really use it.

Hello, i am considering the update but currently i can't give a specific time. Maybe in 1-2 weeks but there will be update. Thanks for your interest.

**Comment by Jackuhlf** [comment]
hey! curious if you have an update? I know its the holidays so i dont expect and dont want you to work on this when you could be spending time with family. just wondering if this project is sitll on your todo list

**Comment by emirhanpisgin** [comment]
yes, probably next week.

**Comment by emirhanpisgin** [comment]
@Jackuhlf the update is here, thanks for your interest and have fun!

> https://modrinth.com/mod/itemframesplus/version/UWKyPRGr
